@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Организация хранения и обработки марок Честного Знака


' Системы
System_Boundary(Марки, "1C:Марки") {
    Container(ОбменКафка, "Обработка Работа с kafka", "")
    Container(ОбменЧЗ, "Обработка Обмен ЧЗ, Пепси (Эмуляцция)", "")
    Container(Сервис, "HTTP сервис Mark", "")
    Container(СправочникМарки, "Справочник Штрихкоды упаковок и товаров", "")
    Container(Номенклатура, "Справочник Номенклатура", "")
    Container(Контрагенты, "Справочник Контрагенты", "")
    Container(КонстантаКафка, "Константа Наименование (Consumers) базы  в Kafka", "")
    Container(Документ, "Документ ДокументЕРП", "")
    Container(РС, "Регистр сведений Статусы_КИ_ЧЗ", "")
    
}


System_Boundary(ЕРП, "1С:Имитация ERP и WMS") {
    Container(Номенклатура1, "Справочник Номенклатура", "")
    Container(Контрагенты1, "Справочник Контрагенты", "")
    Container(ОбменКафка1, "Обработка Работа с kafka", "")
    Container(ОбменВМС, "Обработка Обмен WMS (эмуляция')", "")
    Container(ДокументПО, "Документ Приходный Ордер", "")
    Container(ДокументРО, "Документ Расходный Ордер", "")
    Container(Списание, "Документ Списание", "")
    Container(КонстантаКафка1, "Константа Наименование (Consumers) базы  в Kafka", "")
}


System_Boundary(Кафка, "Kafka"){
    Container(ТопикМарки, "erp.marki", "")
    Container(ТопикНоменклатура, "erp.tovar", "")
}


' Связи
Rel(ОбменКафка, Документ, "Документ и состав марок")
Rel(ОбменКафка, Номенклатура, "Номенклатура")
Rel(ОбменКафка, СправочникМарки, "Марки")
Rel(Кафка, ОбменКафка, "Марки, номенклатура")

Rel(ОбменВМС, ОбменКафка1, "Марки, записанные документы")
Rel(ОбменВМС, ДокументПО, "ПО")
Rel(ОбменВМС, ДокументРО, "РО")
Rel(ОбменВМС, Списание, "Списание")
Rel(ОбменВМС, ОбменКафка1, "Номенклатура")

Rel(ОбменКафка1, ТопикМарки, "Марки")
Rel(ОбменКафка1, ТопикНоменклатура, "Номенклатура")


Rel(Документ, Сервис, "Состав марок")
Rel(СправочникМарки, Сервис, "Состав марок")


Rel(Сервис, ЕРП, "Данные о марках в документе", "http")
Rel(КонстантаКафка, ОбменКафка, "Данные о consumer", "")

Rel(КонстантаКафка1, ОбменКафка1, "Данные о consumer", "")

Rel(ОбменЧЗ, РС, "Данные о составе марок, владельце и статусе", "")


@enduml
