@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Организация хранения и обработки марок Честного Знака


' Системы
System_Boundary(Марки, "1C:Марки") {
    Container_Boundary(Обмен, "Подсистема обмена", "") {
        Container(ОбменКафка, "Обмен с Kafka", "")
        Container(ОбменЧЗ, "Обмен с Честным Знаком", "")
        Container(Сервис, "HTTP сервис", "")
        Container(ОбменПепси, "Обмен с SAP Pepsi ", "")
        }
    Container(Хранение, "Хранение марок, их состава, владельца и статуса ЧЗ", "")
    Container(ХранениеДок, "Хранение данных о марках в документах", "")
}


System(ЕРП, "1С:ERP") {
}

System(ВМС, "1С:WMS") {
}


System(Кафка, "Kafka"){
}


System_Ext(Пепси, "SAP Pepsi")

System_Ext(ЧЗ, "Честный Знак")

' Связи
Rel(ВМС, ЕРП, "Документы")
Rel(ЕРП, Кафка, "Марки в документах, номенклатура")
Rel(Кафка, ОбменКафка, "Марки в документах, номенклатура")

BiRel(Сервис, ЕРП, "Марки в документе, подача команд", "http")
Rel_Back(ОбменПепси, Пепси, "Данные о составе марок и статусе", "stunnel")

Rel_Back(ОбменЧЗ, ЧЗ, "Данные о составе марок, владельце и статусе", "api")


@enduml
