@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Организация хранения и обработки марок Честного Знака


' Системы
System_Boundary(Марки, "1C:Марки") {
    Container(ОбменКафка, "Обмен с Kafka", "")
    Container(ОбменЧЗ, "Обмен с Честным Знаком", "")
    Container(Сервис, "HTTP сервис", "")
    Container(ОбменПепси, "Обмен с SAP Pepsi ", "")
    Container(Хранение, "Хранение данных о марках, их составе, владельце ии статусе ЧЗ", "")
    Container(ХранениеДок, "Хранение данных о марках документов", "")
}


System(ЕРП, "1С:ERP") {
}

System(ВМС, "1С:WMS") {
}


System(Кафка, "Kafka"){
}

System(ВебСервер, "Appache"){
}

System_Ext(Пепси, "SAP Pepsi")

System_Ext(ЧЗ, "Честный Знак")

' Связи
Rel(ВМС, ЕРП, "Документы")
Rel(ЕРП, Кафка, "Марки в документах, номенклатура")
Rel(Кафка, Марки, "Марки в документах, номенклатура")
Rel(ПочтоваяСистема, СотрудникКомпании, "Расчетные листки сотрудникам", "https (ежемесячно)")

Rel_Back(ЗУП, ЛичныйКабинет, "Данные отпуска")
Rel(СотрудникКомпании, ЛичныйКабинет, "Оформление отпуска")

' Обмен с ЕРП
Rel(УчетНСИ, ESB, "Номенклатура", "https")
Rel(ESB, Бухгалтерия, "Номенклатура", "https")

' Расположение
Lay_U(ОтражениеЗП_ЗУП, ЗП_Учет)
Lay_U(СотрудникКомпании, ЛичныйКабинет)

@enduml
