 
Class Справочник.УпаковкиЕдиницыИзмерения {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 -{static} Родитель
	 +{static} Наименование
	 +{static} Код
	 #{static} Безразмерная
	 *{static} Вес
	 -{static} ВесЕдиницаИзмерения
	 *{static} Высота
	 -{static} ВысотаЕдиницаИзмерения
	 *{static} Глубина
	 -{static} ГлубинаЕдиницаИзмерения
	 -{static} ЕдиницаИзмерения
	 *{static} Числитель
	 *{static} Знаменатель
	 +{static} ЛинейныеРазмерыПредставление
	 *{static} Объем
	 -{static} ОбъемЕдиницаИзмерения
	 +{static} СкладскаяГруппа
	 +{static} Типоразмер
	 *{static} Ширина
	 -{static} ШиринаЕдиницаИзмерения
	 *{static} КоличествоУпаковок
	 #{static} ПоставляетсяВМногооборотнойТаре
	 +{static} НоменклатураМногооборотнаяТара
	 +{static} ХарактеристикаМногооборотнаяТара
	 *{static} МинимальноеКоличествоУпаковокМногооборотнойТары
	 +{static} ТипИзмеряемойВеличины
	 +{static} НаименованиеПолное
	 +{static} МеждународноеСокращение
	 +{static} ТипУпаковки
	 +{static} НВД_ДополнительнаяИнформация
	 *{static} НВД_ВесПоДаннымПоставщика
	 *{static} НВД_ВысотаПоДаннымПоставщика
	 *{static} НВД_ГлубинаПоДаннымПоставщика
	 *{static} НВД_ШиринаПоДаннымПоставщика
	 *{static} НВД_ОбъемПоДаннымПоставщика
	 #{static} НВД_ПроверкаВГХ
}
Class Справочник.СерииНоменклатуры {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 ~{static} ГоденДо
	 +{static} ВидНоменклатуры
	 +{static} Номер
	 +{static} НомерКиЗГИСМ
	 +{static} RFIDTID
	 +{static} RFIDUser
	 +{static} RFIDEPC
	 +{static} EPCGTIN
	 ~{static} НВДДатаПроизводства
	 +{static} Номенклатура
	 +{static} НВД_ИнвентарныйКод
	---ДополнительныеРеквизиты---
	 -Свойство
	 Значение
	 +ТекстоваяСтрока
}
Class Справочник.Номенклатура {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
	 +{static} ИдЕРП
}
Class Справочник.Контрагенты {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 +{static} Наименование
	 +{static} Код
	 +{static} ИНН
	 +{static} КПП
	 +{static} ИдЕРП
}
Class Справочник.ШтрихкодыУпаковокТоваров {
	 +{static} ИмяПредопределенныхДанных
	 #{static} Предопределенный
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 -{static} ТипУпаковки
	 -{static} ТипШтрихкода
	 +{static} ЗначениеШтрихкода
	 -{static} Номенклатура
	 -{static} Упаковка
	 *{static} Количество
	 -{static} НВД_Статус
	---ВложенныеТовары---
	 +Номенклатура
	 +Характеристика
	 -Упаковка
	 -Серия
	 *Количество
	 *КоличествоУпаковок
	---ВложенныеШтрихкоды---
	 -Штрихкод
}
Abstract Документ.ДокументЕРП {
	 #{static} Проведен
	 -{static} Ссылка
	 #{static} ПометкаУдаления
	 ~{static} Дата
	 +{static} Номер
	 +{static} ТипДокумента
	 +{static} ИдЕРП
	 +{static} НомерЕРП
	 ~{static} ДатаЕРП
	---НВД_ШтрихкодыУпаковок---
	 -ШтрихкодУпаковки
}
Struct Перечисление.ТипыУпаковок {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} МаркированныйТовар
	 {static} МонотоварнаяУпаковка
	 {static} МультитоварнаяУпаковка
}
Struct Перечисление.ТипыШтрихкодов {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} PDF417
	 {static} DataMatrix
	 {static} ITF14
	 {static} EAN8
	 {static} EAN13
	 {static} Code39
	 {static} Code128
	 {static} SSCC
	 {static} GS1_DataBarExpandedStacked
	 {static} GS1_128
	 {static} QR
	 {static} GS1_DataMatrix
	 {static} Неопределен
}
Struct Перечисление.НВД_СтатусыШтрихКодов {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} Новый
	 {static} Расформирован
	 {static} Изменен
}
Struct Перечисление.СтатусыКодовМаркировкиИСМП {
	 *{static} Порядок
	 -{static} Ссылка
	 {static} Эмитирован
	 {static} Нанесен
	 {static} ВведенВОборот
	 {static} ВведенВОборотПриВозврате
	 {static} Неопределен
	 {static} Экспортирован
	 {static} Утилизирован
	 {static} ВыведенИзОборота
	 {static} ВыведенИзОборотаРозничнаяПродажа
	 {static} ВыведенИзОборотаЭкспортированВСтраныЕАЭС
	 {static} ВыведенИзОборотаЭкспортированЗаПределыСтранЕАЭС
	 {static} ВыведенИзОборотаВозвращенФизическомуЛицу
	 {static} ВыведенИзОборотаПриУтратеИлиПовреждении
	 {static} ВыведенИзОборотаПриУничтожении
	 {static} ВыведенИзОборотаКонфискация
	 {static} ВыведенИзОборотаЛиквидацияПредприятия
	 {static} ВыведенИзОборотаИспользованДляСобственныхНуждПредприятия
	 {static} ВыведенИзОборотаПоДоговоруРассрочки
	 {static} ВыведенИзОборотаПриПеремаркировке
	 {static} ВыведенИзОборотаВРезультатеСписания
	 {static} ВыведенИзОборотаБезвозмезднаяПередача
	 {static} ВыведенИзОборотаПриобретенГосударственнымПредприятием
	 {static} ВыведенИзОборотаПриДистанционнойПродаже
	 {static} Разагрегирован
	 {static} ОжидаетДоставки
	 {static} ОжидаетПовторнойМаркировки
	 {static} ОжидаетПередачуСобственнику
	 {static} НеИспользован
	 {static} Списан
	 {static} ОтрицательноеРешениеФТС
	 {static} ОжидаетПодтверждениеФТС
	 {static} НаКонтролеФТС
	 {static} НаходитсяВСеройЗоне
	 {static} Индивидуализирован
	 {static} НеИндивидуализирован
}
Interface Обработка.РаботаСKafkaЧерезВК {
	 +GroupID_Чтение
	 +Адрес_Запись
	 +Адрес_Просмотр
	 +Адрес_Чтение
	 *Раздел_Запись
	 +Топик_Запись
	 +GroupID_Просмотр
	 #булДанныеПоданыВBase64
	 #ПодпискаТопики_Чтение
	 #булНеЭкранироватьСообщение
	 #ЧитатьДвоичныеДанные
	---тзДанные_Чтение---
	 +key
	 +value
	 +topic
	 +partition
	 +offset
	 +timestamp
	 +headers
	---тзТопикиРазделы_Чтение---
	 +Topic
	 *Partition
	 *Offset
}
Interface Обработка.ОбменЧЗПепси {
}
Entity РегистрСведений.Статусы_КИ_ЧЗ {
---Измерения---
	 +КИ
	 -Номенклатура
---Ресурсы---
	 -ШтрихкодУпаковкиТовара
	 -СтатусКодовМаркировкиИСМП
---Реквизиты---
	 +ИннВладелец
	 -КонтрагентВладелец
	 +ИннВладелец
	 -КонтрагентВладелец
}
Справочник.УпаковкиЕдиницыИзмерения --> Справочник.УпаковкиЕдиницыИзмерения::ВесЕдиницаИзмерения
Справочник.УпаковкиЕдиницыИзмерения --> Справочник.УпаковкиЕдиницыИзмерения::ВысотаЕдиницаИзмерения
Справочник.УпаковкиЕдиницыИзмерения --> Справочник.УпаковкиЕдиницыИзмерения::ГлубинаЕдиницаИзмерения
Справочник.УпаковкиЕдиницыИзмерения --> Справочник.УпаковкиЕдиницыИзмерения::ЕдиницаИзмерения
Справочник.УпаковкиЕдиницыИзмерения --> Справочник.УпаковкиЕдиницыИзмерения::ОбъемЕдиницаИзмерения
Справочник.УпаковкиЕдиницыИзмерения --> Справочник.УпаковкиЕдиницыИзмерения::ШиринаЕдиницаИзмерения
Перечисление.ТипыУпаковок --> Справочник.ШтрихкодыУпаковокТоваров::ТипУпаковки
Перечисление.ТипыШтрихкодов --> Справочник.ШтрихкодыУпаковокТоваров::ТипШтрихкода
Справочник.Номенклатура --> Справочник.ШтрихкодыУпаковокТоваров::Номенклатура
Справочник.УпаковкиЕдиницыИзмерения --> Справочник.ШтрихкодыУпаковокТоваров::Упаковка
Перечисление.НВД_СтатусыШтрихКодов --> Справочник.ШтрихкодыУпаковокТоваров::НВД_Статус
Справочник.УпаковкиЕдиницыИзмерения --> Справочник.ШтрихкодыУпаковокТоваров::Упаковка
Справочник.СерииНоменклатуры --> Справочник.ШтрихкодыУпаковокТоваров::Серия
Справочник.ШтрихкодыУпаковокТоваров --> Справочник.ШтрихкодыУпаковокТоваров::Штрихкод
Справочник.ШтрихкодыУпаковокТоваров --> Документ.ДокументЕРП::ШтрихкодУпаковки
Справочник.Номенклатура --> РегистрСведений.Статусы_КИ_ЧЗ::Номенклатура
Справочник.ШтрихкодыУпаковокТоваров --> РегистрСведений.Статусы_КИ_ЧЗ::ШтрихкодУпаковкиТовара
Перечисление.СтатусыКодовМаркировкиИСМП --> РегистрСведений.Статусы_КИ_ЧЗ::СтатусКодовМаркировкиИСМП
Справочник.Контрагенты --> РегистрСведений.Статусы_КИ_ЧЗ::КонтрагентВладелец
Справочник.Контрагенты --> РегистрСведений.Статусы_КИ_ЧЗ::КонтрагентВладелец

